services:
  django-app:
    build: .
    depends_on:
      mongo:
        condition: service_healthy
    container_name: "django_service"
    ports:
      - "3000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      MONGO_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/${MONGO_INIT}?authSource=admin

  mongo:
    image: mongo:5.0
    ports:
      - "3001:27017"
    volumes:
      - mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INIT}
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username $$MONGO_USERNAME --password $$MONGO_PASSWORD --authenticationDatabase admin --eval \"db.runCommand('ping')\""] 
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo-volume: